using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
//     Runtime Version:4.0.30319.34209
=======
//     Runtime Version:4.0.30319.18408
>>>>>>> 65a7ca033d5f2704e63e47f81995c4cb8fb966d9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("ThoughtWorks Inc.")]
[assembly: AssemblyProductAttribute("CruiseControl.NET")]
<<<<<<< HEAD
[assembly: AssemblyCopyrightAttribute("Copyright © 2003 - 2015 ThoughtWorks Inc.")]
=======
[assembly: AssemblyCopyrightAttribute("Copyright © 2003 - 2014 ThoughtWorks Inc.")]
>>>>>>> 65a7ca033d5f2704e63e47f81995c4cb8fb966d9
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("0.0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("Git hash : 0000000000000000000000000000000000000000")]

